# Generated by Django 2.2.16 on 2022-02-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220215_1124'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='one_following',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_not_author',
        ),
    ]
